### ISSUE TITLE
Javalin 5 is in the works

### ISSUE THREAD

**Issue by tipsy** [jehugaleahsa/javalin-mvc#16]
Hi @jehugaleahsa ! I noticed you just upgraded to v4, and I wanted to tell you that v5 is coming out soon. If you have any feature requests or feedback, now is the time :)

**Comment by jehugaleahsa** [comment]
@tipsy I can give you a summary of how the upgrade went, which may or may not lead to ideas for features. Foremost, it was mostly painless.

## OpenAPI
First, having a single dependency for the OpenAPI stuff is really _nice_. That was a pretty hefty chunk of the example POM in my README. The only problem I ran into was Maven complained about invalid version ranges for `redoc`. I think I tracked it back to different `org.webjars.npm` dependencies pointing to different versions of `yargs`. I solved it for the time being by just excluding redoc, which I don't use anyway:

```xml
<exclusion>
  <groupId>org.webjars.npm</groupId>
  <artifactId>redoc</artifactId>
</exclusion>
```

This was the error message.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project javalin-mvc-test: Resolution of annotationProcessorPath dependencies failed: The artifact has no valid ranges
[ERROR]   org.webjars.npm:yargs:jar:16.0.0-beta.3
[ERROR]
[ERROR] Path to dependency: 
[ERROR]         1) com.google.dagger:dagger-compiler:jar:2.42
[ERROR]         2) com.truncon:javalin-mvc-core:jar:4.0.0-SNAPSHOT
[ERROR]         3) io.javalin:javalin-openapi:jar:4.6.3
[ERROR]         4) org.webjars.npm:redoc:jar:2.0.0-rc.45
[ERROR]         5) org.webjars.npm:swagger2openapi:jar:6.2.3
```

Even though I don't use `redoc`, I guess someone wanting to use this library might. 🤷  It took Maven a _very long time_ to even download all the dependencies. It was like `node_modules` hell in a Java project. 😆 I don't think any of those are your problem. Most likely, this _used to work_ and these libraries' use of ranges ended up breaking it along the way.

## License
I decide I will try to keep my license parallel with whatever license you guys end up using. That will try to make things easier for people wanting to adopt things. MIT and Apache 2.0 are pretty interchangeable, so I don't mind switching.

## Version parity
I also thought it would simplify things if my major version matched your major version. When v5 comes out, I can create a v5. Feature-wise, I don't see much getting added to my library over time. At some point, I will probably give up on my "API" layer and just expose Javalin directly. Right now, classes like `HttpContext` provide a `Object getHandle()` method that gets the Javalin `Context`. I don't really see myself wrapping another library other than Javalin. So, I will probably just add Javalin to the API module's POM and expose it directly.

## Exposing `JsonMapper`
This was our conversation in this issue: https://github.com/javalin/javalin/issues/1572. I was trying to figure out why I need direct access to the `JsonMapper`. The only reason is because I separate my implementation of `HttpContext` from `JavalinHttpContext`. When I implement my `JsonResult` class, it needs to ask the "context" to serialize the JSON, but only when it's asynchronous.

Consider the weird case where someone asks me to serialize a `String` to JSON. If I didn't serialize the `String` to JSON in the async handler for `JsonResult`, I would end up just calling `future("Hello")` instead of `future("\"Hello\"")`, because `future` treats `String` as plain text, by default. I think this is the whole reason you introduced the `callback` argument, so I might be able to simplify my code. I will let you know how that goes!

So two possibilities: 1) I stop trying to make my API stuff independent of Javalin and then I can just directly call `ctx.json(...)` or 2) the callback stuff will allow me to just have a single implementation for both sync/async variants.

## `{param}` vs `:param`
I like that you moved to `{param}`. That could make things like `/api/v{version}/whatever` possible in the future.

One of the primary motivations for introducing Javalin MVC was to avoid needing to constantly parse Strings/JSON into primitives and objects. Frequently, web libraries/frameworks will support a syntax like `{param:int}` to limit the route matching to integer values. For a bad example, you can technically have `/api/users/{userId:int}` and `/api/users/{userId:uuid}` map to different route handlers. Usually, it is to automatically route users to a 400/404 if they pass in a bogus value. I could see type annotations like that for ints, strings, UUIDs, longs, and maybe others (ISO-8601 dates?).

Since Javalin just returns strings under the hood, perhaps this would be bad for performance. The route handler would inspect the path parameter and conclude it is an integer, then throw away the parsed value, and just stick in a string anyway. It's probably better to just handle it as part of the route handler. 🤔 

## App start/stop differences
Some of my unit tests started failing after the upgrade. I think the calls to `start` and `stop` the Javalin app may have changed. Before, I would register to get notified by the events for "server started" and "server stopped". Now, it seems I can just wait for the call to `start` and `stop` to return, and that works fine, so long as I wrap it in a `CompletableFuture.runAsync(...)`.

**Comment by jehugaleahsa** [comment]
Good news! I spent some time looking at the `future` overload taking a callback and that did solve most of my problems. It also allowed me to eliminate half the code in my `ActionResult` classes. Very nice!

The other discovery was the `Context.jsonStream()` and `WsMessageContext.getMessageAsClass()` methods. I just use these directly now, so this eliminated the only reason I needed to pass `JsonMapper` around, so that is good.

It still might be nice to expose `JsonMapper` for people doing extra serialization/deserialization in their handlers. For example, at work, we have JSON in the database and sharing the same `ObjectMapper` could be useful, especially when you need to deal with the Java 8 Date/Time classes.

**Comment by jehugaleahsa** [comment]
The other side to the `JsonMapper` thing is that in a end-user application, they could just pass the same object around via dependency injection, as another alternate. I was thinking last night about how we are also using Jackson to deserialize CSV files at work, too. That's a very different `ObjectMapper`, obviously. People are going to be constructing mappers for different use cases, where JSON is just the one used by Javalin.

**Comment by jehugaleahsa** [comment]
Also, looks like I have some competition: https://github.com/avaje/avaje-http 😆 Looks like the EBean guy again. I think he put something out a while back that used his DI container.

**Comment by tipsy** [comment]
Really great feedback @jehugaleahsa. For the `JsonMapper`, it's available on the `Javalin` instance, so you can easily fetch it with `Javalin#attribute` or `Context#appAttribute`. We could add a dedicated method for it, but since the user is also passing the a `JsonMapper` via `JavalinConfig#jsonMapper`, the user must also have access to the `JsonMapper` in the first place. This means, as you stated, that the user can pass/inject the mapper as they please. So. I'm not sure if the extra methods would be worth it 🤔

**Comment by tipsy** [comment]
> Also, looks like I have some competition: https://github.com/avaje/avaje-http 😆 Looks like the EBean guy again. I think he put something out a while back that used his DI container.

Rob has actually started moving away from Javalin, to a smaller stripped down version which he named *jex*: https://github.com/avaje/avaje-jex

**Comment by jehugaleahsa** [comment]
@tipsy I have always told people to use arrays types with my stuff for parameters, since Jackson needs [extra code](https://www.baeldung.com/jackson-collection-array) to figure them out. Has this come up? Other than tapping directly into Jackson, is there a workaround? I am thinking about adding support for Collection types in my stuff but would rather continue working with `JsonMapper` if possible. I wouldn't want my JSON and non-JSON stuff to work differently.

I noticed the `future(Future, Consumer<Any>)` method I started using isn't very type-safe. I always have to cast it. Would there be any hopes of it being redefined like this?

```java
<T> Context future(CompletableFuture<T> future, Consumer<? super T> callback)
```

**Comment by tipsy** [comment]
> @jehugaleahsa: I noticed the future(Future, Consumer<Any>) method I started using isn't very type-safe. I always have to cast it. Would there be any hopes of it being redefined?

I don't see any reason why not, as long as it works with the rest of the setup. You could have a look at the code and see if you manage to refactor it, or create an issue on the Javalin tracker?

> @jehugaleahsa: @tipsy I have always told people to use arrays types with my stuff for parameters, since Jackson needs [extra code](https://www.baeldung.com/jackson-collection-array) to figure them out. Has this come up? Other than tapping directly into Jackson, is there a workaround? I am thinking about adding support for Collection types in my stuff but would rather continue working with JsonMapper if possible. I wouldn't want my JSON and non-JSON stuff to work differently.

No one has brought it up. I use array types if I have to use Java too.

If you are able to address this in a way that makes sense for all mappers (not just Jackson),
OR if you are able to address it by changing the default Jackson mapper in Javalin
then feel free to submit a PR for it :)

**Comment by jehugaleahsa** [comment]
Javalin MVC 5.x is upgraded. The upgrade went as smooth as expected. I was able to rip out a lot of code when upgrading to the new OpenApi library... that was nice. The `Supplier<CompletableFuture<?>>` and added type-safety are solid improvements, as well.
